# Generated by Django 5.2.4 on 2025-07-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karanaujla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
