# Generated by Django 5.1.4 on 2025-07-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karanaujla', '0003_book_delete_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='buy_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
